<!DOCTYPE html>
<!-- saved from url=(0014)about:internet -->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="x-ua-compatible" content="IE=9" >

<title>Prediction of Exercise Quality</title>

<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 12px;
   margin: 8px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 { 
   font-size:2.2em; 
}

h2 { 
   font-size:1.8em; 
}

h3 { 
   font-size:1.4em; 
}

h4 { 
   font-size:1.0em; 
}

h5 { 
   font-size:0.9em; 
}

h6 { 
   font-size:0.8em; 
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre {	
   margin-top: 0;
   max-width: 95%;
   border: 1px solid #ccc;
   white-space: pre-wrap;
}

pre code {
   display: block; padding: 0.5em;
}

code.r, code.cpp {
   background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * { 
      background: transparent !important; 
      color: black !important; 
      filter:none !important; 
      -ms-filter: none !important; 
   }

   body { 
      font-size:12pt; 
      max-width:100%; 
   }
       
   a, a:visited { 
      text-decoration: underline; 
   }

   hr { 
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote { 
      padding-right: 1em; 
      page-break-inside: avoid; 
   }

   tr, img { 
      page-break-inside: avoid; 
   }

   img { 
      max-width: 100% !important; 
   }

   @page :left { 
      margin: 15mm 20mm 15mm 10mm; 
   }
     
   @page :right { 
      margin: 15mm 10mm 15mm 20mm; 
   }

   p, h2, h3 { 
      orphans: 3; widows: 3; 
   }

   h2, h3 { 
      page-break-after: avoid; 
   }
}

</style>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: rgb(88, 72, 246)
   }

   pre .number {
     color: rgb(0, 0, 205);
   }

   pre .comment {
     color: rgb(76, 136, 107);
   }

   pre .keyword {
     color: rgb(0, 0, 255);
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: rgb(3, 106, 7);
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>




</head>

<body>
<h1>Prediction of Exercise Quality</h1>

<h2>Synopsis</h2>

<p>Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. </p>

<p>The goal of this project is to predict the manner in which people perform certain exercises. The data for this project come from this source: 
<a href="http://groupware.les.inf.puc-rio.br/har">http://groupware.les.inf.puc-rio.br/har</a>.</p>

<p>This data was collected from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways.</p>

<h2>Data Processing</h2>

<h4>Loading the required R Packages</h4>

<pre><code class="r">opts_chunk$set(echo = TRUE, results = &quot;asis&quot;, cache = TRUE)
</code></pre>

<pre><code class="r">library(caret)
library(xtable)
</code></pre>

<h4>Reading the data file in R</h4>

<pre><code class="r">train = read.csv(&quot;pml-training.csv&quot;, header = TRUE)
</code></pre>

<h4>Training Set and Cross Validation Data</h4>

<p>The above data was further divided into a training set and Cross Validation set. 75% of the data was used as training set and 25% for test set.Partition was performed on the variable &#39;Classe&#39;. This is the dependent variable in this analysis and needs to be predicted based on other variables.</p>

<pre><code class="r">partition = createDataPartition(y = train$classe, p = 0.75, list = FALSE)
train_set = train[partition, ]
cv_set = train[-partition, ]
dim(train_set)
</code></pre>

<p>[1] 14718   160</p>

<pre><code class="r">dim(cv_set)
</code></pre>

<p>[1] 4904  160</p>

<h4>Reducing the number of predictors</h4>

<p>Printed out the column named for better understanding the content of the data</p>

<pre><code class="r">names(train_set)
</code></pre>

<p>[1] &ldquo;X&rdquo;                        &ldquo;user_name&rdquo;<br/>
  [3] &ldquo;raw_timestamp_part_1&rdquo;     &ldquo;raw_timestamp_part_2&rdquo;<br/>
  [5] &ldquo;cvtd_timestamp&rdquo;           &ldquo;new_window&rdquo;<br/>
  [7] &ldquo;num_window&rdquo;               &ldquo;roll_belt&rdquo;<br/>
  [9] &ldquo;pitch_belt&rdquo;               &ldquo;yaw_belt&rdquo;<br/>
 [11] &ldquo;total_accel_belt&rdquo;         &ldquo;kurtosis_roll_belt&rdquo;<br/>
 [13] &ldquo;kurtosis_picth_belt&rdquo;      &ldquo;kurtosis_yaw_belt&rdquo;<br/>
 [15] &ldquo;skewness_roll_belt&rdquo;       &ldquo;skewness_roll_belt.1&rdquo;<br/>
 [17] &ldquo;skewness_yaw_belt&rdquo;        &ldquo;max_roll_belt&rdquo;<br/>
 [19] &ldquo;max_picth_belt&rdquo;           &ldquo;max_yaw_belt&rdquo;<br/>
 [21] &ldquo;min_roll_belt&rdquo;            &ldquo;min_pitch_belt&rdquo;<br/>
 [23] &ldquo;min_yaw_belt&rdquo;             &ldquo;amplitude_roll_belt&rdquo;<br/>
 [25] &ldquo;amplitude_pitch_belt&rdquo;     &ldquo;amplitude_yaw_belt&rdquo;<br/>
 [27] &ldquo;var_total_accel_belt&rdquo;     &ldquo;avg_roll_belt&rdquo;<br/>
 [29] &ldquo;stddev_roll_belt&rdquo;         &ldquo;var_roll_belt&rdquo;<br/>
 [31] &ldquo;avg_pitch_belt&rdquo;           &ldquo;stddev_pitch_belt&rdquo;<br/>
 [33] &ldquo;var_pitch_belt&rdquo;           &ldquo;avg_yaw_belt&rdquo;<br/>
 [35] &ldquo;stddev_yaw_belt&rdquo;          &ldquo;var_yaw_belt&rdquo;<br/>
 [37] &ldquo;gyros_belt_x&rdquo;             &ldquo;gyros_belt_y&rdquo;<br/>
 [39] &ldquo;gyros_belt_z&rdquo;             &ldquo;accel_belt_x&rdquo;<br/>
 [41] &ldquo;accel_belt_y&rdquo;             &ldquo;accel_belt_z&rdquo;<br/>
 [43] &ldquo;magnet_belt_x&rdquo;            &ldquo;magnet_belt_y&rdquo;<br/>
 [45] &ldquo;magnet_belt_z&rdquo;            &ldquo;roll_arm&rdquo;<br/>
 [47] &ldquo;pitch_arm&rdquo;                &ldquo;yaw_arm&rdquo;<br/>
 [49] &ldquo;total_accel_arm&rdquo;          &ldquo;var_accel_arm&rdquo;<br/>
 [51] &ldquo;avg_roll_arm&rdquo;             &ldquo;stddev_roll_arm&rdquo;<br/>
 [53] &ldquo;var_roll_arm&rdquo;             &ldquo;avg_pitch_arm&rdquo;<br/>
 [55] &ldquo;stddev_pitch_arm&rdquo;         &ldquo;var_pitch_arm&rdquo;<br/>
 [57] &ldquo;avg_yaw_arm&rdquo;              &ldquo;stddev_yaw_arm&rdquo;<br/>
 [59] &ldquo;var_yaw_arm&rdquo;              &ldquo;gyros_arm_x&rdquo;<br/>
 [61] &ldquo;gyros_arm_y&rdquo;              &ldquo;gyros_arm_z&rdquo;<br/>
 [63] &ldquo;accel_arm_x&rdquo;              &ldquo;accel_arm_y&rdquo;<br/>
 [65] &ldquo;accel_arm_z&rdquo;              &ldquo;magnet_arm_x&rdquo;<br/>
 [67] &ldquo;magnet_arm_y&rdquo;             &ldquo;magnet_arm_z&rdquo;<br/>
 [69] &ldquo;kurtosis_roll_arm&rdquo;        &ldquo;kurtosis_picth_arm&rdquo;<br/>
 [71] &ldquo;kurtosis_yaw_arm&rdquo;         &ldquo;skewness_roll_arm&rdquo;<br/>
 [73] &ldquo;skewness_pitch_arm&rdquo;       &ldquo;skewness_yaw_arm&rdquo;<br/>
 [75] &ldquo;max_roll_arm&rdquo;             &ldquo;max_picth_arm&rdquo;<br/>
 [77] &ldquo;max_yaw_arm&rdquo;              &ldquo;min_roll_arm&rdquo;<br/>
 [79] &ldquo;min_pitch_arm&rdquo;            &ldquo;min_yaw_arm&rdquo;<br/>
 [81] &ldquo;amplitude_roll_arm&rdquo;       &ldquo;amplitude_pitch_arm&rdquo;<br/>
 [83] &ldquo;amplitude_yaw_arm&rdquo;        &ldquo;roll_dumbbell&rdquo;<br/>
 [85] &ldquo;pitch_dumbbell&rdquo;           &ldquo;yaw_dumbbell&rdquo;<br/>
 [87] &ldquo;kurtosis_roll_dumbbell&rdquo;   &ldquo;kurtosis_picth_dumbbell&rdquo; 
 [89] &ldquo;kurtosis_yaw_dumbbell&rdquo;    &ldquo;skewness_roll_dumbbell&rdquo;<br/>
 [91] &ldquo;skewness_pitch_dumbbell&rdquo;  &ldquo;skewness_yaw_dumbbell&rdquo;<br/>
 [93] &ldquo;max_roll_dumbbell&rdquo;        &ldquo;max_picth_dumbbell&rdquo;<br/>
 [95] &ldquo;max_yaw_dumbbell&rdquo;         &ldquo;min_roll_dumbbell&rdquo;<br/>
 [97] &ldquo;min_pitch_dumbbell&rdquo;       &ldquo;min_yaw_dumbbell&rdquo;<br/>
 [99] &ldquo;amplitude_roll_dumbbell&rdquo;  &ldquo;amplitude_pitch_dumbbell&rdquo;
[101] &ldquo;amplitude_yaw_dumbbell&rdquo;   &ldquo;total_accel_dumbbell&rdquo;<br/>
[103] &ldquo;var_accel_dumbbell&rdquo;       &ldquo;avg_roll_dumbbell&rdquo;<br/>
[105] &ldquo;stddev_roll_dumbbell&rdquo;     &ldquo;var_roll_dumbbell&rdquo;<br/>
[107] &ldquo;avg_pitch_dumbbell&rdquo;       &ldquo;stddev_pitch_dumbbell&rdquo;<br/>
[109] &ldquo;var_pitch_dumbbell&rdquo;       &ldquo;avg_yaw_dumbbell&rdquo;<br/>
[111] &ldquo;stddev_yaw_dumbbell&rdquo;      &ldquo;var_yaw_dumbbell&rdquo;<br/>
[113] &ldquo;gyros_dumbbell_x&rdquo;         &ldquo;gyros_dumbbell_y&rdquo;<br/>
[115] &ldquo;gyros_dumbbell_z&rdquo;         &ldquo;accel_dumbbell_x&rdquo;<br/>
[117] &ldquo;accel_dumbbell_y&rdquo;         &ldquo;accel_dumbbell_z&rdquo;<br/>
[119] &ldquo;magnet_dumbbell_x&rdquo;        &ldquo;magnet_dumbbell_y&rdquo;<br/>
[121] &ldquo;magnet_dumbbell_z&rdquo;        &ldquo;roll_forearm&rdquo;<br/>
[123] &ldquo;pitch_forearm&rdquo;            &ldquo;yaw_forearm&rdquo;<br/>
[125] &ldquo;kurtosis_roll_forearm&rdquo;    &ldquo;kurtosis_picth_forearm&rdquo;<br/>
[127] &ldquo;kurtosis_yaw_forearm&rdquo;     &ldquo;skewness_roll_forearm&rdquo;<br/>
[129] &ldquo;skewness_pitch_forearm&rdquo;   &ldquo;skewness_yaw_forearm&rdquo;<br/>
[131] &ldquo;max_roll_forearm&rdquo;         &ldquo;max_picth_forearm&rdquo;<br/>
[133] &ldquo;max_yaw_forearm&rdquo;          &ldquo;min_roll_forearm&rdquo;<br/>
[135] &ldquo;min_pitch_forearm&rdquo;        &ldquo;min_yaw_forearm&rdquo;<br/>
[137] &ldquo;amplitude_roll_forearm&rdquo;   &ldquo;amplitude_pitch_forearm&rdquo; 
[139] &ldquo;amplitude_yaw_forearm&rdquo;    &ldquo;total_accel_forearm&rdquo;<br/>
[141] &ldquo;var_accel_forearm&rdquo;        &ldquo;avg_roll_forearm&rdquo;<br/>
[143] &ldquo;stddev_roll_forearm&rdquo;      &ldquo;var_roll_forearm&rdquo;<br/>
[145] &ldquo;avg_pitch_forearm&rdquo;        &ldquo;stddev_pitch_forearm&rdquo;<br/>
[147] &ldquo;var_pitch_forearm&rdquo;        &ldquo;avg_yaw_forearm&rdquo;<br/>
[149] &ldquo;stddev_yaw_forearm&rdquo;       &ldquo;var_yaw_forearm&rdquo;<br/>
[151] &ldquo;gyros_forearm_x&rdquo;          &ldquo;gyros_forearm_y&rdquo;<br/>
[153] &ldquo;gyros_forearm_z&rdquo;          &ldquo;accel_forearm_x&rdquo;<br/>
[155] &ldquo;accel_forearm_y&rdquo;          &ldquo;accel_forearm_z&rdquo;<br/>
[157] &ldquo;magnet_forearm_x&rdquo;         &ldquo;magnet_forearm_y&rdquo;<br/>
[159] &ldquo;magnet_forearm_z&rdquo;         &ldquo;classe&rdquo;                  </p>

<p>Based on the column names and further understanding of the data from reading about the experiment, noted that the first 7 variable are classifier variable for people/time. These do not represent any form of measurement and hence cannot be used to predict the outcome. Updated the training data set by removing these variables. </p>

<pre><code class="r">train_set_2 = train_set[, c(8:160)]
</code></pre>

<p>Next removed the variables which have near zero variability across the data as these variables cannot account for change in outcome. The nearZeroVar function generates an array of TRUE/FALSE.Used this array to update the train data set.</p>

<pre><code class="r">nsv_2 = nearZeroVar(train_set_2, saveMetrics = FALSE)
train_set_3 = train_set_2[, -nsv_2]
</code></pre>

<p>Next removed the variables with missing values.Such variables can do more harm than good in the prediction function. The reason could be that value for a particular case is missing or skewed for a certain outcome. In such scenario, including these predictors can result in wrong prediction models.</p>

<pre><code class="r">Missing_Val = apply(train_set_3, 2, function(x) {
    sum(is.na(x))
})

train_set_4 = train_set_3[, which(Missing_Val == 0)]
dim(train_set_4)
</code></pre>

<p>[1] 14718    53</p>

<p>Now 52 predictors and the variable to be predicted are left. Since there is neither a documentation of how these variables affect the outcome nor I have the technical expertise in this domain, I decided to go ahead with using all these predictors in the model. Singular Value Decomposition was considered but refrained from it as it would make the result less interpretable.</p>

<p>A random forest method with cross validation method was used for prediction model. Since this model already checks for cross validation, a separate cross validation was not applied.</p>

<pre><code class="r">fit_model_1 = train(classe ~ ., data = train_set_4, method = &quot;rf&quot;, trControl = trainControl(method = &quot;cv&quot;, 
    number = 10, allowParallel = TRUE))
</code></pre>

<pre><code>## Loading required package: randomForest
## randomForest 4.6-7
## Type rfNews() to see new features/changes/bug fixes.
</code></pre>

<p>The following results were obtained. </p>

<pre><code class="r">print_data = xtable(fit_model_1$results, digits = 4)
print(print_data, digits = 4, type = &quot;html&quot;)
</code></pre>

<!-- html table generated in R 3.0.3 by xtable 1.7-3 package -->

<!-- Sun Jun 22 20:24:09 2014 -->

<TABLE border=1>
<TR> <TH>  </TH> <TH> mtry </TH> <TH> Accuracy </TH> <TH> Kappa </TH> <TH> AccuracySD </TH> <TH> KappaSD </TH>  </TR>
  <TR> <TD align="right"> 1 </TD> <TD align="right"> 2.0000 </TD> <TD align="right"> 0.9929 </TD> <TD align="right"> 0.9910 </TD> <TD align="right"> 0.0026 </TD> <TD align="right"> 0.0033 </TD> </TR>
  <TR> <TD align="right"> 2 </TD> <TD align="right"> 27.0000 </TD> <TD align="right"> 0.9929 </TD> <TD align="right"> 0.9911 </TD> <TD align="right"> 0.0024 </TD> <TD align="right"> 0.0031 </TD> </TR>
  <TR> <TD align="right"> 3 </TD> <TD align="right"> 52.0000 </TD> <TD align="right"> 0.9894 </TD> <TD align="right"> 0.9866 </TD> <TD align="right"> 0.0026 </TD> <TD align="right"> 0.0032 </TD> </TR>
   </TABLE>

<p>This appeared to be a highly accurate model with about 99.3% accuracy on the training set. Thus the &#39;In sample error&#39; is 0.7%.  </p>

<p>Now an estimate of out sample error is required. For this, the cross validation data set was used. Before using the cv data, similar transformations were applied on that data. Basically, only the predictors selected for training were included.</p>

<pre><code class="r">c_names = names(train_set_4)
cv_set_2 = cv_set[, c_names]
cv_pred = predict(fit_model_1, cv_set_2)
</code></pre>

<p>A confusion matrix was used to estimate the out sample error.</p>

<pre><code class="r">cf = confusionMatrix(cv_pred, cv_set_2$classe)
print_data = xtable(cf$table, digits = 4)
print(print_data, type = &quot;html&quot;, digits = 4)
</code></pre>

<!-- html table generated in R 3.0.3 by xtable 1.7-3 package -->

<!-- Sun Jun 22 20:34:34 2014 -->

<TABLE border=1>
<TR> <TH>  </TH> <TH> A </TH> <TH> B </TH> <TH> C </TH> <TH> D </TH> <TH> E </TH>  </TR>
  <TR> <TD align="right"> A </TD> <TD align="right">  1389 </TD> <TD align="right">     3 </TD> <TD align="right">     0 </TD> <TD align="right">     0 </TD> <TD align="right">     0 </TD> </TR>
  <TR> <TD align="right"> B </TD> <TD align="right">     6 </TD> <TD align="right">   944 </TD> <TD align="right">     4 </TD> <TD align="right">     0 </TD> <TD align="right">     0 </TD> </TR>
  <TR> <TD align="right"> C </TD> <TD align="right">     0 </TD> <TD align="right">     2 </TD> <TD align="right">   848 </TD> <TD align="right">    10 </TD> <TD align="right">     0 </TD> </TR>
  <TR> <TD align="right"> D </TD> <TD align="right">     0 </TD> <TD align="right">     0 </TD> <TD align="right">     3 </TD> <TD align="right">   794 </TD> <TD align="right">     1 </TD> </TR>
  <TR> <TD align="right"> E </TD> <TD align="right">     0 </TD> <TD align="right">     0 </TD> <TD align="right">     0 </TD> <TD align="right">     0 </TD> <TD align="right">   900 </TD> </TR>
   </TABLE>

<pre><code class="r">print_data = xtable(cf$byClass)
print(print_data, type = &quot;html&quot;)
</code></pre>

<!-- html table generated in R 3.0.3 by xtable 1.7-3 package -->

<!-- Sun Jun 22 20:34:34 2014 -->

<TABLE border=1>
<TR> <TH>  </TH> <TH> Sensitivity </TH> <TH> Specificity </TH> <TH> Pos Pred Value </TH> <TH> Neg Pred Value </TH> <TH> Prevalence </TH> <TH> Detection Rate </TH> <TH> Detection Prevalence </TH> <TH> Balanced Accuracy </TH>  </TR>
  <TR> <TD align="right"> Class: A </TD> <TD align="right"> 1.00 </TD> <TD align="right"> 1.00 </TD> <TD align="right"> 1.00 </TD> <TD align="right"> 1.00 </TD> <TD align="right"> 0.28 </TD> <TD align="right"> 0.28 </TD> <TD align="right"> 0.28 </TD> <TD align="right"> 1.00 </TD> </TR>
  <TR> <TD align="right"> Class: B </TD> <TD align="right"> 0.99 </TD> <TD align="right"> 1.00 </TD> <TD align="right"> 0.99 </TD> <TD align="right"> 1.00 </TD> <TD align="right"> 0.19 </TD> <TD align="right"> 0.19 </TD> <TD align="right"> 0.19 </TD> <TD align="right"> 1.00 </TD> </TR>
  <TR> <TD align="right"> Class: C </TD> <TD align="right"> 0.99 </TD> <TD align="right"> 1.00 </TD> <TD align="right"> 0.99 </TD> <TD align="right"> 1.00 </TD> <TD align="right"> 0.17 </TD> <TD align="right"> 0.17 </TD> <TD align="right"> 0.18 </TD> <TD align="right"> 0.99 </TD> </TR>
  <TR> <TD align="right"> Class: D </TD> <TD align="right"> 0.99 </TD> <TD align="right"> 1.00 </TD> <TD align="right"> 0.99 </TD> <TD align="right"> 1.00 </TD> <TD align="right"> 0.16 </TD> <TD align="right"> 0.16 </TD> <TD align="right"> 0.16 </TD> <TD align="right"> 0.99 </TD> </TR>
  <TR> <TD align="right"> Class: E </TD> <TD align="right"> 1.00 </TD> <TD align="right"> 1.00 </TD> <TD align="right"> 1.00 </TD> <TD align="right"> 1.00 </TD> <TD align="right"> 0.18 </TD> <TD align="right"> 0.18 </TD> <TD align="right"> 0.18 </TD> <TD align="right"> 1.00 </TD> </TR>
   </TABLE>

<pre><code class="r">cf$overall
</code></pre>

<pre><code>  Accuracy          Kappa  AccuracyLower  AccuracyUpper   AccuracyNull 
    0.9941         0.9925         0.9915         0.9960         0.2845 
</code></pre>

<p>AccuracyPValue  McnemarPValue 
        0.0000            NaN </p>

<p>Noted the even the accuracy of model on cross validation data set (99.4%) was even better that on the training set. Hence the estimated &#39;Out Sample error&#39; is 0.6%</p>

<p>Also applied the same model to test data for obtaining the predictions.</p>

<pre><code class="r">test = read.csv(&quot;pml-testing.csv&quot;, header = TRUE)
t_names = c_names[-53]
test_2 = test[, t_names]
test_pred = predict(fit_model_1, test_2)
</code></pre>

<p>The result obtained were as below.</p>

<pre><code class="r">test_pred
</code></pre>

<p>[1] B A B A A E D B A A B C B A E E A B B B
Levels: A B C D E</p>

<h2>End of File</h2>

</body>

</html>

